# -*- coding: utf-8 -*-
"""rag_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mwh7k52Bng9m8wkmNccMOV1-L5d-62A0
"""

# ============================================
# RAG CUSTOMER SUPPORT CHATBOT - COMPLETE WORKING
# Copy ALL of this into ONE Colab cell and run
# ============================================

import warnings
warnings.filterwarnings('ignore')

print("="*60)
print("🤖 RAG CUSTOMER SUPPORT ASSISTANT")
print("="*60)

# ============================================
# KNOWLEDGE BASE
# ============================================
SUPPORT_KNOWLEDGE = {
    "returns_refunds": {
        "keywords": ["return", "refund", "money back", "exchange", "reimbursement"],
        "answer": "You can return items within 30 days of purchase for a full refund. Items must be unused and in original packaging. Refunds are processed within 5-7 business days to your original payment method.",
        "policy_details": "Return shipping is free for defective items. For other returns, customer pays return shipping."
    },
    "shipping_delivery": {
        "keywords": ["shipping", "delivery", "track", "tracking", "arrive", "where is my order"],
        "answer": "Standard shipping takes 3-5 business days. Express shipping takes 1-2 business days. Free shipping on orders over $50. You'll receive a tracking number via email within 24 hours of shipment.",
        "policy_details": "International shipping available to 50+ countries. Delivery times vary by location."
    },
    "account_management": {
        "keywords": ["account", "login", "password", "sign up", "register", "create account", "forgot password"],
        "answer": "To create an account, click 'Sign Up' on our website. For password reset, use 'Forgot Password' on the login page. Account deletion requests can be submitted to support.",
        "policy_details": "Account deletion takes 30 days to complete per data protection regulations."
    },
    "order_management": {
        "keywords": ["order", "cancel", "change order", "modify", "wrong item"],
        "answer": "Orders can be cancelled within 1 hour of placement. Contact support immediately with your order number. After 1 hour, you may need to process a return once received.",
        "policy_details": "Order modifications after shipping may incur additional fees."
    },
    "warranty": {
        "keywords": ["warranty", "broken", "defect", "repair", "damaged", "not working"],
        "answer": "All products come with a 1-year manufacturer's warranty covering defects in materials and workmanship. Accidental damage is not covered. Contact support with your order number to file a claim.",
        "policy_details": "Extended warranty available for purchase within 30 days of product delivery."
    },
    "contact_support": {
        "keywords": ["contact", "email", "phone", "call", "speak", "human", "agent", "talk to person"],
        "answer": "Email: support@example.com | Phone: 1-800-555-0123 | Live Chat: Available on website. Hours: Monday-Friday 9 AM to 6 PM EST, Saturday 10 AM to 2 PM EST.",
        "policy_details": "Emergency support available 24/7 for urgent issues."
    },
    "payment_billing": {
        "keywords": ["payment", "credit card", "bill", "charged", "pay", "checkout"],
        "answer": "We accept Visa, Mastercard, American Express, PayPal, and Apple Pay. All payments are secure and encrypted. Billing issues can be resolved by contacting our billing department.",
        "policy_details": "Subscription billing occurs on the same day each month."
    },
    "product_info": {
        "keywords": ["product", "specifications", "features", "size", "dimensions", "color"],
        "answer": "Product specifications are available on each product page. For detailed questions, please refer to the product manual or contact our product specialists.",
        "policy_details": "New products added monthly. Sign up for newsletter for updates."
    }
}

print(f"✅ Loaded {len(SUPPORT_KNOWLEDGE)} support categories")

# ============================================
# INTENT DETECTION
# ============================================
def detect_intent(question):
    """Detect customer intent from question"""
    q = question.lower()

    best_intent = "general"
    best_score = 0.0

    for intent, data in SUPPORT_KNOWLEDGE.items():
        score = 0
        keywords = data['keywords']

        for keyword in keywords:
            if keyword in q:
                score += 1

        if keywords:
            score = score / len(keywords)

        if score > best_score:
            best_score = score
            best_intent = intent

    if best_score > 0.5:
        best_score = min(best_score + 0.2, 1.0)

    return best_intent, best_score

print("✅ Intent detection ready")

# ============================================
# SIMPLE RAG RETRIEVAL (No vector DB needed)
# ============================================
def retrieve_answer(question, intent):
    """Retrieve answer based on intent"""
    if intent in SUPPORT_KNOWLEDGE:
        return [SUPPORT_KNOWLEDGE[intent]["answer"]]
    return []

# ============================================
# RESPONSE GENERATION
# ============================================
def generate_response(question, intent, answers, confidence):
    """Generate friendly response"""

    templates = {
        "returns_refunds": "💰 I understand you need help with a return or refund. ",
        "shipping_delivery": "📦 Let me help you with shipping and delivery information. ",
        "account_management": "🔐 I can help with your account-related questions. ",
        "order_management": "📝 I'll assist you with your order. ",
        "warranty": "🛡️ Let me help you with warranty information. ",
        "contact_support": "💬 I'll help you connect with our support team. ",
        "payment_billing": "💳 Let me assist with payment and billing. ",
        "product_info": "📋 I can help with product information. ",
        "general": "🤝 Thank you for reaching out. "
    }

    prefix = templates.get(intent, templates["general"])

    if answers:
        main_answer = answers[0]
    else:
        main_answer = "I want to help, but I need more information. Could you please provide more details?"

    confidence_note = ""
    if confidence < 0.5:
        confidence_note = "\n\n⚠️ I'm not completely sure. Type 'human' to speak to an agent."
    elif confidence < 0.7:
        confidence_note = "\n\n📌 Type 'human' if this doesn't answer your question."

    return prefix + main_answer + confidence_note

# ============================================
# HUMAN-IN-THE-LOOP (HITL)
# ============================================
def human_escalation(user_question, bot_response, reason):
    """Handle HITL escalation"""
    print("\n" + "="*50)
    print("👨‍💼 HUMAN-IN-THE-LOOP ESCALATION")
    print("="*50)
    print(f"📋 Reason: {reason}")
    print(f"👤 Question: {user_question}")
    print(f"🤖 Bot said: {bot_response}")
    print("-"*50)
    print("📢 Notifying available agents...")

    human_response = input("👨‍💼 Human Agent Response: ")
    print("="*50)
    return human_response

# ============================================
# MAIN CHATBOT FUNCTION
# ============================================
def run_chatbot():
    """Main chatbot execution"""

    print("\n💡 Instructions:")
    print("   • Type your question naturally")
    print("   • Type 'human' to speak to a real person")
    print("   • Type 'status' to see system stats")
    print("   • Type 'exit' to quit\n")

    session_stats = {
        "total_queries": 0,
        "human_escalations": 0,
        "intents_detected": {}
    }

    while True:
        print("-"*50)
        user_input = input("👤 Customer: ").strip()

        if user_input.lower() in ['exit', 'quit', 'bye']:
            print("\n" + "="*50)
            print("📊 SESSION SUMMARY")
            print("="*50)
            print(f"📈 Total Queries: {session_stats['total_queries']}")
            print(f"👨‍💼 Human Escalations: {session_stats['human_escalations']}")
            if session_stats['total_queries'] > 0:
                resolution_rate = (session_stats['total_queries'] - session_stats['human_escalations']) / session_stats['total_queries'] * 100
                print(f"🤖 Bot Resolution Rate: {resolution_rate:.0f}%")
            print("\n👋 Thank you for contacting customer support!")
            break

        if not user_input:
            continue

        session_stats["total_queries"] += 1

        # Direct human request
        if user_input.lower() in ['human', 'agent', 'talk to human', 'real person']:
            print("\n🔄 Transferring to human support...")
            human_response = human_escalation(user_input, "User requested human", "Direct human request")
            print(f"\n👨‍💼 Agent: {human_response}\n")
            session_stats["human_escalations"] += 1
            continue

        # Status check
        if user_input.lower() == 'status':
            print(f"\n📊 System Status:")
            print(f"   • Queries processed: {session_stats['total_queries']}")
            print(f"   • Human handoffs: {session_stats['human_escalations']}")
            print(f"   • Active intents: {len(SUPPORT_KNOWLEDGE)}")
            print(f"   • RAG System: Active\n")
            continue

        # Step 1: Detect intent
        intent, confidence = detect_intent(user_input)
        session_stats["intents_detected"][intent] = session_stats["intents_detected"].get(intent, 0) + 1
        print(f"🎯 Intent: {intent} | Confidence: {int(confidence*100)}%")

        # Step 2: Retrieve answer
        answers = retrieve_answer(user_input, intent)
        print(f"📚 Retrieved {len(answers)} relevant answers")

        # Step 3: Generate response
        response = generate_response(user_input, intent, answers, confidence)

        # Step 4: Check if HITL needed
        if confidence < 0.5 or len(answers) == 0:
            print("⚠️ Low confidence - escalating to human...")
            response = human_escalation(user_input, response, f"Low confidence ({confidence:.0%})")
            session_stats["human_escalations"] += 1

        # Step 5: Output
        print(f"\n🤖 Assistant: {response}\n")

# ============================================
# RUN THE CHATBOT
# ============================================
run_chatbot()